export type CurrencyInfo = {
  country: string
  code: string
  name: string
}

/**
 * All world countries with their official currency (ISO 4217 code).
 * Sorted alphabetically by country name. Several countries share a currency
 * (e.g. EUR, USD, XOF, XAF, XCD, AUD) — each country is still listed so users
 * can find their currency by country name.
 */
export const CURRENCIES: CurrencyInfo[] = [
  { country: 'Afghanistan', code: 'AFN', name: 'Afghan Afghani' },
  { country: 'Albania', code: 'ALL', name: 'Albanian Lek' },
  { country: 'Algeria', code: 'DZD', name: 'Algerian Dinar' },
  { country: 'Andorra', code: 'EUR', name: 'Euro' },
  { country: 'Angola', code: 'AOA', name: 'Angolan Kwanza' },
  { country: 'Antigua and Barbuda', code: 'XCD', name: 'East Caribbean Dollar' },
  { country: 'Argentina', code: 'ARS', name: 'Argentine Peso' },
  { country: 'Armenia', code: 'AMD', name: 'Armenian Dram' },
  { country: 'Australia', code: 'AUD', name: 'Australian Dollar' },
  { country: 'Austria', code: 'EUR', name: 'Euro' },
  { country: 'Azerbaijan', code: 'AZN', name: 'Azerbaijani Manat' },
  { country: 'Bahamas', code: 'BSD', name: 'Bahamian Dollar' },
  { country: 'Bahrain', code: 'BHD', name: 'Bahraini Dinar' },
  { country: 'Bangladesh', code: 'BDT', name: 'Bangladeshi Taka' },
  { country: 'Barbados', code: 'BBD', name: 'Barbadian Dollar' },
  { country: 'Belarus', code: 'BYN', name: 'Belarusian Ruble' },
  { country: 'Belgium', code: 'EUR', name: 'Euro' },
  { country: 'Belize', code: 'BZD', name: 'Belize Dollar' },
  { country: 'Benin', code: 'XOF', name: 'West African CFA Franc' },
  { country: 'Bhutan', code: 'BTN', name: 'Bhutanese Ngultrum' },
  { country: 'Bolivia', code: 'BOB', name: 'Bolivian Boliviano' },
  { country: 'Bosnia and Herzegovina', code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark' },
  { country: 'Botswana', code: 'BWP', name: 'Botswanan Pula' },
  { country: 'Brazil', code: 'BRL', name: 'Brazilian Real' },
  { country: 'Brunei', code: 'BND', name: 'Brunei Dollar' },
  { country: 'Bulgaria', code: 'BGN', name: 'Bulgarian Lev' },
  { country: 'Burkina Faso', code: 'XOF', name: 'West African CFA Franc' },
  { country: 'Burundi', code: 'BIF', name: 'Burundian Franc' },
  { country: 'Cabo Verde', code: 'CVE', name: 'Cape Verdean Escudo' },
  { country: 'Cambodia', code: 'KHR', name: 'Cambodian Riel' },
  { country: 'Cameroon', code: 'XAF', name: 'Central African CFA Franc' },
  { country: 'Canada', code: 'CAD', name: 'Canadian Dollar' },
  { country: 'Central African Republic', code: 'XAF', name: 'Central African CFA Franc' },
  { country: 'Chad', code: 'XAF', name: 'Central African CFA Franc' },
  { country: 'Chile', code: 'CLP', name: 'Chilean Peso' },
  { country: 'China', code: 'CNY', name: 'Chinese Yuan' },
  { country: 'Colombia', code: 'COP', name: 'Colombian Peso' },
  { country: 'Comoros', code: 'KMF', name: 'Comorian Franc' },
  { country: 'Congo (Democratic Republic)', code: 'CDF', name: 'Congolese Franc' },
  { country: 'Congo (Republic)', code: 'XAF', name: 'Central African CFA Franc' },
  { country: 'Costa Rica', code: 'CRC', name: 'Costa Rican Colon' },
  { country: "Cote d'Ivoire", code: 'XOF', name: 'West African CFA Franc' },
  { country: 'Croatia', code: 'EUR', name: 'Euro' },
  { country: 'Cuba', code: 'CUP', name: 'Cuban Peso' },
  { country: 'Cyprus', code: 'EUR', name: 'Euro' },
  { country: 'Czechia', code: 'CZK', name: 'Czech Koruna' },
  { country: 'Denmark', code: 'DKK', name: 'Danish Krone' },
  { country: 'Djibouti', code: 'DJF', name: 'Djiboutian Franc' },
  { country: 'Dominica', code: 'XCD', name: 'East Caribbean Dollar' },
  { country: 'Dominican Republic', code: 'DOP', name: 'Dominican Peso' },
  { country: 'Ecuador', code: 'USD', name: 'US Dollar' },
  { country: 'Egypt', code: 'EGP', name: 'Egyptian Pound' },
  { country: 'El Salvador', code: 'USD', name: 'US Dollar' },
  { country: 'Equatorial Guinea', code: 'XAF', name: 'Central African CFA Franc' },
  { country: 'Eritrea', code: 'ERN', name: 'Eritrean Nakfa' },
  { country: 'Estonia', code: 'EUR', name: 'Euro' },
  { country: 'Eswatini', code: 'SZL', name: 'Swazi Lilangeni' },
  { country: 'Ethiopia', code: 'ETB', name: 'Ethiopian Birr' },
  { country: 'Fiji', code: 'FJD', name: 'Fijian Dollar' },
  { country: 'Finland', code: 'EUR', name: 'Euro' },
  { country: 'France', code: 'EUR', name: 'Euro' },
  { country: 'Gabon', code: 'XAF', name: 'Central African CFA Franc' },
  { country: 'Gambia', code: 'GMD', name: 'Gambian Dalasi' },
  { country: 'Georgia', code: 'GEL', name: 'Georgian Lari' },
  { country: 'Germany', code: 'EUR', name: 'Euro' },
  { country: 'Ghana', code: 'GHS', name: 'Ghanaian Cedi' },
  { country: 'Greece', code: 'EUR', name: 'Euro' },
  { country: 'Grenada', code: 'XCD', name: 'East Caribbean Dollar' },
  { country: 'Guatemala', code: 'GTQ', name: 'Guatemalan Quetzal' },
  { country: 'Guinea', code: 'GNF', name: 'Guinean Franc' },
  { country: 'Guinea-Bissau', code: 'XOF', name: 'West African CFA Franc' },
  { country: 'Guyana', code: 'GYD', name: 'Guyanese Dollar' },
  { country: 'Haiti', code: 'HTG', name: 'Haitian Gourde' },
  { country: 'Honduras', code: 'HNL', name: 'Honduran Lempira' },
  { country: 'Hungary', code: 'HUF', name: 'Hungarian Forint' },
  { country: 'Iceland', code: 'ISK', name: 'Icelandic Krona' },
  { country: 'India', code: 'INR', name: 'Indian Rupee' },
  { country: 'Indonesia', code: 'IDR', name: 'Indonesian Rupiah' },
  { country: 'Iran', code: 'IRR', name: 'Iranian Rial' },
  { country: 'Iraq', code: 'IQD', name: 'Iraqi Dinar' },
  { country: 'Ireland', code: 'EUR', name: 'Euro' },
  { country: 'Israel', code: 'ILS', name: 'Israeli New Shekel' },
  { country: 'Italy', code: 'EUR', name: 'Euro' },
  { country: 'Jamaica', code: 'JMD', name: 'Jamaican Dollar' },
  { country: 'Japan', code: 'JPY', name: 'Japanese Yen' },
  { country: 'Jordan', code: 'JOD', name: 'Jordanian Dinar' },
  { country: 'Kazakhstan', code: 'KZT', name: 'Kazakhstani Tenge' },
  { country: 'Kenya', code: 'KES', name: 'Kenyan Shilling' },
  { country: 'Kiribati', code: 'AUD', name: 'Australian Dollar' },
  { country: 'Kuwait', code: 'KWD', name: 'Kuwaiti Dinar' },
  { country: 'Kyrgyzstan', code: 'KGS', name: 'Kyrgystani Som' },
  { country: 'Laos', code: 'LAK', name: 'Laotian Kip' },
  { country: 'Latvia', code: 'EUR', name: 'Euro' },
  { country: 'Lebanon', code: 'LBP', name: 'Lebanese Pound' },
  { country: 'Lesotho', code: 'LSL', name: 'Lesotho Loti' },
  { country: 'Liberia', code: 'LRD', name: 'Liberian Dollar' },
  { country: 'Libya', code: 'LYD', name: 'Libyan Dinar' },
  { country: 'Liechtenstein', code: 'CHF', name: 'Swiss Franc' },
  { country: 'Lithuania', code: 'EUR', name: 'Euro' },
  { country: 'Luxembourg', code: 'EUR', name: 'Euro' },
  { country: 'Madagascar', code: 'MGA', name: 'Malagasy Ariary' },
  { country: 'Malawi', code: 'MWK', name: 'Malawian Kwacha' },
  { country: 'Malaysia', code: 'MYR', name: 'Malaysian Ringgit' },
  { country: 'Maldives', code: 'MVR', name: 'Maldivian Rufiyaa' },
  { country: 'Mali', code: 'XOF', name: 'West African CFA Franc' },
  { country: 'Malta', code: 'EUR', name: 'Euro' },
  { country: 'Marshall Islands', code: 'USD', name: 'US Dollar' },
  { country: 'Mauritania', code: 'MRU', name: 'Mauritanian Ouguiya' },
  { country: 'Mauritius', code: 'MUR', name: 'Mauritian Rupee' },
  { country: 'Mexico', code: 'MXN', name: 'Mexican Peso' },
  { country: 'Micronesia', code: 'USD', name: 'US Dollar' },
  { country: 'Moldova', code: 'MDL', name: 'Moldovan Leu' },
  { country: 'Monaco', code: 'EUR', name: 'Euro' },
  { country: 'Mongolia', code: 'MNT', name: 'Mongolian Tugrik' },
  { country: 'Montenegro', code: 'EUR', name: 'Euro' },
  { country: 'Morocco', code: 'MAD', name: 'Moroccan Dirham' },
  { country: 'Mozambique', code: 'MZN', name: 'Mozambican Metical' },
  { country: 'Myanmar', code: 'MMK', name: 'Burmese Kyat' },
  { country: 'Namibia', code: 'NAD', name: 'Namibian Dollar' },
  { country: 'Nauru', code: 'AUD', name: 'Australian Dollar' },
  { country: 'Nepal', code: 'NPR', name: 'Nepalese Rupee' },
  { country: 'Netherlands', code: 'EUR', name: 'Euro' },
  { country: 'New Zealand', code: 'NZD', name: 'New Zealand Dollar' },
  { country: 'Nicaragua', code: 'NIO', name: 'Nicaraguan Cordoba' },
  { country: 'Niger', code: 'XOF', name: 'West African CFA Franc' },
  { country: 'Nigeria', code: 'NGN', name: 'Nigerian Naira' },
  { country: 'North Korea', code: 'KPW', name: 'North Korean Won' },
  { country: 'North Macedonia', code: 'MKD', name: 'Macedonian Denar' },
  { country: 'Norway', code: 'NOK', name: 'Norwegian Krone' },
  { country: 'Oman', code: 'OMR', name: 'Omani Rial' },
  { country: 'Pakistan', code: 'PKR', name: 'Pakistani Rupee' },
  { country: 'Palau', code: 'USD', name: 'US Dollar' },
  { country: 'Palestine', code: 'ILS', name: 'Israeli New Shekel' },
  { country: 'Panama', code: 'USD', name: 'US Dollar' },
  { country: 'Papua New Guinea', code: 'PGK', name: 'Papua New Guinean Kina' },
  { country: 'Paraguay', code: 'PYG', name: 'Paraguayan Guarani' },
  { country: 'Peru', code: 'PEN', name: 'Peruvian Sol' },
  { country: 'Philippines', code: 'PHP', name: 'Philippine Peso' },
  { country: 'Poland', code: 'PLN', name: 'Polish Zloty' },
  { country: 'Portugal', code: 'EUR', name: 'Euro' },
  { country: 'Qatar', code: 'QAR', name: 'Qatari Riyal' },
  { country: 'Romania', code: 'RON', name: 'Romanian Leu' },
  { country: 'Russia', code: 'RUB', name: 'Russian Ruble' },
  { country: 'Rwanda', code: 'RWF', name: 'Rwandan Franc' },
  { country: 'Saint Kitts and Nevis', code: 'XCD', name: 'East Caribbean Dollar' },
  { country: 'Saint Lucia', code: 'XCD', name: 'East Caribbean Dollar' },
  { country: 'Saint Vincent and the Grenadines', code: 'XCD', name: 'East Caribbean Dollar' },
  { country: 'Samoa', code: 'WST', name: 'Samoan Tala' },
  { country: 'San Marino', code: 'EUR', name: 'Euro' },
  { country: 'Sao Tome and Principe', code: 'STN', name: 'Sao Tome and Principe Dobra' },
  { country: 'Saudi Arabia', code: 'SAR', name: 'Saudi Riyal' },
  { country: 'Senegal', code: 'XOF', name: 'West African CFA Franc' },
  { country: 'Serbia', code: 'RSD', name: 'Serbian Dinar' },
  { country: 'Seychelles', code: 'SCR', name: 'Seychellois Rupee' },
  { country: 'Sierra Leone', code: 'SLE', name: 'Sierra Leonean Leone' },
  { country: 'Singapore', code: 'SGD', name: 'Singapore Dollar' },
  { country: 'Slovakia', code: 'EUR', name: 'Euro' },
  { country: 'Slovenia', code: 'EUR', name: 'Euro' },
  { country: 'Solomon Islands', code: 'SBD', name: 'Solomon Islands Dollar' },
  { country: 'Somalia', code: 'SOS', name: 'Somali Shilling' },
  { country: 'South Africa', code: 'ZAR', name: 'South African Rand' },
  { country: 'South Korea', code: 'KRW', name: 'South Korean Won' },
  { country: 'South Sudan', code: 'SSP', name: 'South Sudanese Pound' },
  { country: 'Spain', code: 'EUR', name: 'Euro' },
  { country: 'Sri Lanka', code: 'LKR', name: 'Sri Lankan Rupee' },
  { country: 'Sudan', code: 'SDG', name: 'Sudanese Pound' },
  { country: 'Suriname', code: 'SRD', name: 'Surinamese Dollar' },
  { country: 'Sweden', code: 'SEK', name: 'Swedish Krona' },
  { country: 'Switzerland', code: 'CHF', name: 'Swiss Franc' },
  { country: 'Syria', code: 'SYP', name: 'Syrian Pound' },
  { country: 'Taiwan', code: 'TWD', name: 'Taiwan Dollar' },
  { country: 'Tajikistan', code: 'TJS', name: 'Tajikistani Somoni' },
  { country: 'Tanzania', code: 'TZS', name: 'Tanzanian Shilling' },
  { country: 'Thailand', code: 'THB', name: 'Thai Baht' },
  { country: 'Timor-Leste', code: 'USD', name: 'US Dollar' },
  { country: 'Togo', code: 'XOF', name: 'West African CFA Franc' },
  { country: 'Tonga', code: 'TOP', name: "Tongan Pa'anga" },
  { country: 'Trinidad and Tobago', code: 'TTD', name: 'Trinidad and Tobago Dollar' },
  { country: 'Tunisia', code: 'TND', name: 'Tunisian Dinar' },
  { country: 'Turkey', code: 'TRY', name: 'Turkish Lira' },
  { country: 'Turkmenistan', code: 'TMT', name: 'Turkmenistani Manat' },
  { country: 'Tuvalu', code: 'AUD', name: 'Australian Dollar' },
  { country: 'Uganda', code: 'UGX', name: 'Ugandan Shilling' },
  { country: 'Ukraine', code: 'UAH', name: 'Ukrainian Hryvnia' },
  { country: 'United Arab Emirates', code: 'AED', name: 'UAE Dirham' },
  { country: 'United Kingdom', code: 'GBP', name: 'British Pound' },
  { country: 'United States', code: 'USD', name: 'US Dollar' },
  { country: 'Uruguay', code: 'UYU', name: 'Uruguayan Peso' },
  { country: 'Uzbekistan', code: 'UZS', name: 'Uzbekistani Sum' },
  { country: 'Vanuatu', code: 'VUV', name: 'Vanuatu Vatu' },
  { country: 'Vatican City', code: 'EUR', name: 'Euro' },
  { country: 'Venezuela', code: 'VES', name: 'Venezuelan Bolivar' },
  { country: 'Vietnam', code: 'VND', name: 'Vietnamese Dong' },
  { country: 'Yemen', code: 'YER', name: 'Yemeni Rial' },
  { country: 'Zambia', code: 'ZMW', name: 'Zambian Kwacha' },
  { country: 'Zimbabwe', code: 'ZWL', name: 'Zimbabwean Dollar' },
]

/** Unique list of currency codes (for lookups / symbol mapping). */
export const CURRENCY_CODES: string[] = Array.from(new Set(CURRENCIES.map((c) => c.code)))

/** Unique, sorted list of country names (for country dropdowns). */
export const COUNTRIES: string[] = Array.from(new Set(CURRENCIES.map((c) => c.country))).sort()

/** Find a currency entry by its code (first matching country). */
export function getCurrencyByCode(code: string): CurrencyInfo | undefined {
  return CURRENCIES.find((c) => c.code === code)
}
